# Generated by Django 2.1.5 on 2019-03-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20190226_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='author',
        ),
        migrations.RemoveField(
            model_name='note',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
